# Dockerfile for WordPress
FROM wordpress:latest

# Example of additional steps you might do in the future
# RUN apt-get update && apt-get install -y ...

# Copy your WordPress custom code or plugins if needed
# COPY ./my-theme /var/www/html/wp-content/themes/

EXPOSE 80
